server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      client-id: producer-1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.serialization.AvroSerializer
logging:
  level:
    org:
      springframework:
        web:
          client:
            org.springframework.web.client.RestTemplate: DEBUG
config:
  sensorEventsTopic: telemetry.sensors.v1
  hubEventsTopic: telemetry.hubs.v1


